# Generated by Django 5.0.2 on 2024-02-22 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_stuff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
