# Generated by Django 5.0.2 on 2024-02-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stuff_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='left_time',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='came',
            field=models.BooleanField(default=False),
        ),
    ]
